merge phpdoc2rst 0.0.3
ridi/phpdoc2rst pull request #1
Opened 2018-10-31 07:28 UTC by sunsidew

2018-10-31 07:53 UTC, luaneyed requested changes
일단 1차로 리뷰 남깁니다~ ㅎㅎ

2018-10-31 07:53 UTC, luaneyed commented on composer.json
>    "name": "ridibooks/doxphp2rst-with-depth",
이름도 `phpdoc2rst`로 하면 좋을 것 같습니다.

2018-10-31 07:53 UTC, luaneyed commented on composer.json
>    "license": "MIT",
`bin/phpdoc2rst` 파일을 최상위로 빼고
https://getcomposer.org/doc/articles/vendor-binaries.md#how-is-it-defined- 으로 `composer.json`에 `bin` 설정해주면

지금보다 더 짧은 커맨드로 실행할 수 있을 것 같아요.

2018-10-31 07:53 UTC, luaneyed commented on .gitignore
> +vendor
`.idea`도 추가 부탁드려요~

2018-10-31 07:53 UTC, luaneyed commented on composer.json
>    "require": {
php version constraint 추가 부탁드립니다.

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +<?php
https://www.php-fig.org/psr/psr-1/#23-side-effects

하나의 PHP File은 declaration만 있거나, side effect만 있는 것이 좋습니다.
이건 실행 파일이니까, declaration들을 다른 파일로 모으고, 여기서 사용해주세요~

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +    $file_cmd = array();
`array()` 대신 `[]`을 사용해주세요~

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +function combineMultiCmds($cmd_list) {
implode (http://php.net/manual/kr/function.implode.php) 함수를 이용하시면 될 것 같습니다.

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +        if(is_dir($path) && $value != "." && $value != "..") {
`!=` 대신 `!==`을 이용하면 좋습니다.

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +    foreach($file_cmd as $cmd) { exec($cmd); }
https://www.php-fig.org/psr/psr-2/#55-foreach

loop 구조는 항상 { 뒤에 개행합니다.

2018-10-31 07:53 UTC, luaneyed commented on bin/phpdoc2rst
> +    if (!$first_dir) exec("echo \"\" >> " . makeIdxRstFilePath($root_prefix));
저희는 conditional block에서 `{}`을  항상 사용합니다.

2018-11-05 08:19 UTC, sunsidew commented
@luaneyed 🙇

2018-11-06 01:21 UTC, luaneyed requested changes
2차 리뷰입니다~~

2018-11-06 01:21 UTC, luaneyed commented on composer.json
> +  "version": "0.0.3",
php 파일들은 전부 namespace를 붙여주세요~

Handler 내부의 파일들은 `PhpDoc2Rst\Handler`로,
Util 내부의 파일들은 `PhpDoc2Rst\Util`로 하시면 될 것 같습니다.

아마 `composer.json`의 `autoload` 속성을 쓰시면 좋을 것 같습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +require_once LIB_DIR.'/Handler/StringHandler.php';
말씀드린 대로 모든 파일에 namespace를 붙이면, php 파일 간 참조는 항상 `use`로 할 수 있게 됩니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +
모든 php 파일의 `<?php` 바로 아랫 줄에 `declare(strict_types=1);`을 적어주세요~
https://github.com/ridi/style-guide/tree/master/PHP#%ED%83%80%EC%9E%85-%EC%A7%80%EC%A0%95

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +     * FileHandler constructor.
요 줄은 자동 생성되지만 생성될 때마다 지워주세요~ ㅎㅎ

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +        $this->target_src = 'src/'.$top_prefix;
`"src/$top_prefix"` 간단할 경우에는 항상 이렇게 써주면 좋습니다~

2018-11-06 01:21 UTC, luaneyed commented on composer.json
>    }
https://github.com/ridi/style-guide/blob/master/PHP/.php_cs
https://github.com/ridi/library-php/blob/master/ruleset.xml
위 두 파일을 프로젝트 root에 포함시켜주세요~

그리고 https://github.com/ridi/style-guide/tree/master/PHP#php-codesniffer-%EC%82%AC%EC%9A%A9 이 설정을 하시면

아마 PhpStorm이 linting 오류를 체크해줄 텐데, 다 고쳐주시면 좋을 것 같습니다. ㅎㅎ

2018-11-06 01:21 UTC, luaneyed commented on lib/Util/Constant.php
> +define('ROOT_DIR', $argv[1]);
`FileHandler` constructor parameter로 `$root_dir`을 받고, `phpdoc2rst`가 `$argv[1]`을 넘겨주도록 변경해주세요~

그러면 밑의 두 상수들도 `FileHandler`의 instance variable로 저장하거나, 아예 없앨 수 있습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Util/Constant.php
> +define('LIB_DIR', __DIR__.'/..');
namespace를 사용하면 이 상수 없이도 할 수 있습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/StringHandler.php
> +    public function setDirDocName(string $dir_doc_name)
return이 없으면 끝에 `: void` 적어주세요~

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/StringHandler.php
> +    public function makeIdxRstFilePath($prefix) {
parameter type과 return type이 이 class에 많이 없네요 ㅎㅎ

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +    function getDirContents($dir, $root_prefix) {
visibility가 빠졌습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    function initProgressBar($src_path) {
visibility가 빠졌습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Util/Argv.php
> +<?php
아마 고치시다 보면 이 내용이 `phpdoc2rst`로 가게 될 것 같은데요,

그래도 이 로직을 분리를 하고 싶으시면
```
class Argv
{
public static function validate(array $args): bool
or
public static function validate(array $args): ?string (returns error message or null)
or
public static function validate(array $args): void (throws exception if there is error) -> 권장
}
```
이렇게 하신 다음에 사용처에서 결과를 가지고 handling하시는 것이 좋습니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        $this->file_cnt = 1;
어떻게 constructing하든지 이렇게 초기 값이 고정인 경우
그냥 `private $file_cnt = 1;` 해주면 깔끔합니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +        foreach($files as $key => $file_name){
`$key`가 안 쓰이고 있네요.

그냥 `foreach($files as $file_name)` 하시면 됩니다.

2018-11-06 01:21 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +              exec($this->strHandler->makeRstTitleCmd("/$my_name") . " > " . $this->strHandler->makeIdxRstFilePath("$root_prefix/$my_name"));
한 줄 120자를 웬만하면 지켜주셔요~~ ㅎㅎ

2018-11-08 02:47 UTC, luaneyed requested changes
마지막 리뷰입니다~

2018-11-08 02:47 UTC, luaneyed commented on bin/phpdoc2rst
> +    InputInspector::validate($argv);
`$argv[1]`이 `$root_dir`이라는 정보가 이곳과 `InputInspector::validate` 두 군데에 분산되어 있습니다.
`$root_dir = InputInput::getRootDir($argv);` 처럼 하면 한 군데서만 알아도 될 것 같습니다.

2018-11-08 02:47 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    public function addProgress(): void
이 함수에 phpdocs 자동 생성 하시면 throws 태그가 생성될 거에요~ 사용처도 그렇게 부탁드립니다.

2018-11-08 02:47 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        }
이건 마음에 안드시면 안 하셔도 됩니다.

[참고] Little more functional code

```
        $total_php_cnt = count(
            array_filter(
                iterator_to_array(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($src_path))),
                function (\SplFileInfo $file): bool {
                    return $file->getExtension() === 'PHP';
                }
            )
        );
```

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +        foreach ($file_cmd as $cmd)
앞은 복수형, 뒤는 단수형이어야 맞겠죠?
ex1) `$cmd_list as $cmd`
es2) `$commands as $command`

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/StringHandler.php
> +    public function addRstListChildCmd(string $name, bool &$first_dir): string
(`&$first_dir`)
closure가 아닌, class method는 parameter에 `&`을 쓰지 않는 것이 좋습니다. 사용처에서 변수 흐름 파악이 어려워집니다.

https://github.com/ridi/style-guide/tree/master/PHP#%ED%83%80%EC%9E%85-%EC%A7%80%EC%A0%95

---

이 함수의 호출처가 `if(is_dir)` 내부여서, 이 함수를 사용한 뒤에 호출처에서 update 해주면 될 것 같습니다.

2018-11-08 02:47 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        {
foreach, for, while, do while 등은 `{` 전에 개행하지 않습니다.
아마 phpcs ruleset 설정이 잘 안되신 것 같습니다 ㅠㅠ

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/StringHandler.php
> +    public function setDirDocName(string $dir_doc_name): void
이 함수는 쓰이지 않고 있는 것 같네요~
그렇다면 member variable도 없애고, (유지하려면 `private const`로)
이 클래스 내의 함수들도 다 public static function 으로 만들 수 있을 것 같습니다.

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +    public function __construct(string $root_dir, string $top_prefix = 'Ridibooks')
`store/store` 말고도 여러 곳에서 많이 쓰일 것으로 예상되고 오픈 소스이기 때문에, ` = 'Ridibooks'`는 없는 것이 좋아 보입니다~

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/StringHandler.php
> +        return "$prefix/$this->dir_doc_name.rst";
`DIRECTORY_SEPARATOR`라는 상수를 사용하셨던데, 상수만 쓰던지 `/`만 쓰던지 하면 좀 더 일관성이 있지 않을까요? ㅎㅎ

저 개인적으로는 그냥 `/`가 가독성이 더 좋을 것 같습니다.

2018-11-08 02:47 UTC, luaneyed commented on composer.json
> +  "description": "convert doxphp to rst with directory structure.",
`authors` 항목 작성 부탁드립니다.

참고
https://github.com/ridi/library-php/blob/master/composer.json#L5
https://github.com/ridi/style-guide/blob/master/OSS.md#github-%EA%B4%80%EB%A6%AC

2018-11-08 02:47 UTC, luaneyed commented on composer.json
> +  "description": "convert doxphp to rst with directory structure.",
`Convert PHPDoc to ~`가 맞을 것 같습니다.

2018-11-08 02:47 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +        $files = scandir($dir);
return 값이 `false`일 경우 적절한 대응 부탁드립니다.

2018-11-08 02:50 UTC, luaneyed commented on composer.json
> +  "name": "ridibooks/phpdoc2rst",
php 프로젝트면 모두 적용 가능하기 때문에 `ridi/phpdoc2rst`가 더 좋을 것 같습니다.

참고 : https://github.com/ridi/style-guide/tree/master/PHP#%EC%9D%98%EC%A1%B4%EC%84%B1-%EA%B4%80%EB%A6%AC-composer

2018-11-08 05:56 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        $this->progressBar = $this->initProgressBar($src_path);
`$this->progressBar = $this->createProgressBar($src_path);`
`$this->initProgressBar($src_path);`

위 둘 중 하나의 형태로 하는 것이 적절해 보입니다.

2018-11-08 07:19 UTC, sunsidew commented on lib/Util/ProgressBar.php
> +        }
👍

2018-11-08 10:53 UTC, sunsidew commented on lib/Util/ProgressBar.php
> +        $this->progressBar = $this->initProgressBar($src_path);
🙇

2018-11-12 01:36 UTC, luaneyed commented on lib/Util/InputInspector.php
>      public static function validate(array $argv): void
로직을 getRootDir 안으로 옮기는 것이 좋을 것 같습니다. 이 함수의 맥락은 `getRootDir`이 아니면 이해할 수 없습니다.

2018-11-13 07:06 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +    private $target_src = "src/Ridibooks/Api";
target_src도 마찬가지로 store/store 에서만 쓰는 것이 아니기 때문에 root_dir처럼 argument로 받는 것이 좋겠습니다.

1. docs_dir
2. target_src

위 두 가지를 argument로 받는 것으로 하는 것이 어떨까요? 이를 테면 다음의 의도를 가지고 실행하도록요.
'target_src 내부의 php file들의 docs를 rst로 바꿔서 docs_dir에 저장해라'

`\PhpDoc2Rst\Handler\CommandHandler::convertRstCmd`에서는 root_dir을 단독으로 쓰고 있는데요, 그건 다음과 같이 root_dir 없이 처리 가능합니다.

1. https://github.com/ridi/doxphp 에서 composer.json 에 bin 추가
2. 결국 참조하는 두 doxphp bin들은 `phpdoc2rst`와 동일 directory에 놓이게 될 것이므로 상대경로로 참조 가능

🙇

2018-11-13 07:13 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        $this->file_cnt += 1;
`$this->file_cnt`의 초기값을 0으로 하고, update 전에 1 늘리는 것이 코드의 의도와 더 잘 맞을 것 같습니다.

2018-11-13 07:25 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +            if (!realpath($top_path) && !file_exists($top_path) && !is_dir($top_path) && pathinfo($top_path, PATHINFO_EXTENSION) === "") {
`$top_path`가 존재하기는 하는데 디렉토리가 아니면....
그렇다고 맘대로 날리기도 그렇고...
exception인 것 같습니다.....

2018-11-14 10:23 UTC, luaneyed commented on .php_cs
> +//$finder = PhpCsFixer\Finder::create()
요 주석 안 쓰시는 거면 지우는게 좋겠네요~

2018-11-14 10:40 UTC, luaneyed requested changes
진짜 마지막이기를~ 🙏🏻

2018-11-14 10:40 UTC, luaneyed commented on bin/phpdoc2rst
> +    $handler = new FileHandler($target_paths);
세 개 쪼개서 넘겨주는 게 좋을 것 같아요~

`InputInspector::getTargetDirPaths` 의 return을 위한 dto class를 만들면 이상적이지만... 그냥 여기서 쪼개주는 정도로만 해도 될 것 같습니다~ `이건 bin, source, doc의 array다`라는게 암묵적이라 최대한 짧게 유지하는게 좋아서요 ㅎㅎ

2018-11-14 10:40 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    public static function initProgressBar($src_path): Manager
1. string type 적어주세요~
2. 이제는 `public static function create`로 의미가 바뀐 것 같습니다.

2018-11-14 10:40 UTC, luaneyed commented on lib/Handler/FileHandler.php
> +                    throw new Exception("Target path directory includes file name.");
요거 혹시 phpstorm이 표시 안 해주나요~?

1. `\Exception`으로 사용
2. `use Exception`

둘 중 하나로 부탁드려요~

2018-11-14 10:40 UTC, luaneyed commented on bin/phpdoc2rst
> +    $handler->convertDocsToRsts();
```
$converter = new Converter($target_paths);
$converter->execute();
```
```
PhpDoc2Rst::convert($target_paths); (이 경우 private constructor로 전환)
```
위와 같이 하는게 좀 더 의미가 와닿지 않을까요? ㅎㅎ bin을 통하지 않고 php class를 직접 이용할 수도 있어서, 다른 건 아니더라도 convert interface만은 좀 더 예쁘면 좋을 것 같아요~

2018-11-15 03:16 UTC, sunsidew commented on bin/phpdoc2rst
> +    $handler = new FileHandler($target_paths);
이거 아예 이렇게 가져가서, FileHandler constructor에서 파라미터 별로 받는건 별로일까요.
```suggestion
$handler = new FileHandler(InputInspector::getTargetDirPaths($argv));
```

2018-11-15 03:39 UTC, sunsidew commented on bin/phpdoc2rst
> +    $handler->convertDocsToRsts();
이거 converter 클래스 새로 만들고, bin/phpdoc2rst도 별도 클래스로 만들자는게 맞을까요?

2018-11-15 05:18 UTC, luaneyed commented on bin/phpdoc2rst
> +    $handler->convertDocsToRsts();
첫 번째 예시
rename `FileHandler` to `Converter`
rename `convertDocsToRsts` to `execute`

두 번째 예시
rename `FileHandler` to `PhpDoc2Rst`
construct를 private으로 변경
rename `convertDocsToRsts` to `convert`, then add parameters to `convert`

을 저는 생각했었습니다~

2018-11-15 05:23 UTC, luaneyed commented on bin/phpdoc2rst
> +    $handler = new FileHandler($target_paths);
넵 맨 아래 코멘트의 내용도 포함하는 건데, `FileHandler`를 어디서든 사용할 수 있도록 파라미터가 명확한 것이 좋겠습니다.
예를 들면 constructor의 phpdocs에 `이거, 이거, 이거의 array`라고 쓸 수도 있겠지만, 그러면 그냥 세 개를 따로 받는 것이 더 나을 것 같습니다.

InputInspector가 associative array를 return하도록 변경한다면, dto class 없이도 array의 순서에 의존하지 않을 수도 있습니다. http://php.net/manual/en/migration71.new-features.php#migration71.new-features.support-for-keys-in-list

2018-11-15 07:12 UTC, luaneyed requested changes
진짜 마지막입니다.

2018-11-15 07:12 UTC, luaneyed commented on lib/Handler/Converter.php
> +    private function initRootDir(): void
@throws 추가해주세요~

2018-11-15 07:12 UTC, luaneyed commented on lib/Handler/Converter.php
> +        $this->progressBarManager = ProgressBar::create($source_dir_path);
execute를 여러 번 호출할 수 있으므로, 아래 두 줄은 execute로 옮기는 것이 좋을 것 같습니다.
```
$this->initRootDir();
$this->progressBarManager = ProgressBar::create($source_dir_path);
```

2018-11-15 07:12 UTC, luaneyed commented on lib/Handler/Converter.php
> +class Converter
이건 `PhpDoc2Rst` namespace(상위 디렉토리)에 놓는 것이 좋지 않을까요?
`Handler`라는 의미가 별로 없는 것 같기도 하고, 사용처에서 이거만 가져다 쓰면 되기 때문에 최상위 namespace에 놓으면 좋을 것 같습니다.

2018-11-16 03:29 UTC, luaneyed commented on bin/phpdoc2rst
> +        $target_path_list["bin_dir_path"],
1. 인자로 받을 필요 없이 이 파일에서 `__DIR__`으로 가져와서 쓰면 되지 않을까요?
2. 만약 이렇게 받아야 한다면, `README.md` 업데이트 해주셔야 할 것 같아요~

2018-11-16 06:01 UTC, luaneyed approved these changes
Squash Merge 부탁드려요~

2018-11-16 06:06 UTC, sunsidew commented
@luaneyed 고생하셨습니다

2018-11-16 06:23 UTC, merged