Fix for update progressbar at specific percent interval.
ridi/phpdoc2rst pull request #2
Opened 2018-12-26 07:29 UTC by sunsidew

2018-12-27 06:32 UTC, luaneyed requested changes

2018-12-27 06:32 UTC, luaneyed commented on lib/Converter.php
> +        $this->total_php_file_cnt = $this->countPhpFiles($source_dir_path);
`execute`를 호출할 때마다 바뀔 수도 있으니, `execute` 안으로 옮기는 것이 좋을 것 같습니다.

2018-12-27 06:32 UTC, luaneyed commented on lib/Converter.php
> +                        $this->progressPercent);
괄호 앞에서 개행해야 합니다.

2018-12-27 06:32 UTC, luaneyed commented on lib/Converter.php
> +    private function countPhpFiles(string $src_path) {
`{` 앞에서 개행해야 합니다.

2018-12-27 06:32 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    public static function updateProgressBar(int $total_cnt, int $current_cnt, Manager $manager, int $current_perc): int {
`ProgressBar`가 `Manager`와 `total_cnt`를 내장하고, `create`는 `self`를 return하고, 이 함수는 `public function advance()`로 바꿔서 구현할 수 있습니다. 이 클래스와 호출처 둘 다 깔끔해질거에요.

2018-12-28 07:41 UTC, sunsidew commented on lib/Util/ProgressBar.php
> +    public static function updateProgressBar(int $total_cnt, int $current_cnt, Manager $manager, int $current_perc): int {
@luaneyed 이게 원래는 말씀하신 구조였다가, Manager 객체의 관리를 Converter에 일임하는 구조로 바뀌고 static하게 가져갔던걸로 기억합니다. 혹 해당 책임 여부/관리의 고려가 필요할까요?

2018-12-28 09:14 UTC, namenu commented on lib/Converter.php
> +    private $converted_php_file_cnt;
Converter가 progress 표시를 위한 상태를 가지는 것은 좋지 않은 커플링 같습니다.

2018-12-28 09:26 UTC, sunsidew commented on lib/Converter.php
> +    private $converted_php_file_cnt;
넵 그래서 기존 ProgressBar 일임 구조로 변경 중에 있습니다 :)

2019-01-02 05:15 UTC, luaneyed requested changes

2019-01-02 05:15 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        $this->proceed_php_cnt += 1;
이게 함수의 맨 위로 가야 하지 않을까요?

2019-01-02 05:15 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    public function advance()
`: void` 적어주세요~

2019-01-02 05:15 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    public function __construct($total_php_cnt)
`int` type 적어주세요

2019-01-02 05:15 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +        if ($current_perc >= $this->current_interval_perc) {
[질문] 이렇게 하는건 성능 때문인가요?

2019-01-02 05:15 UTC, luaneyed commented on lib/Converter.php
> +    private function countPhpFiles(string $src_path)
1. `: int`가 있으면 좋을 것 같습니다.
2. parameter를 받지 말거나, static function으로 바꾸거나 둘 중 하나로 하면 좋을 것 같습니다.

2019-01-02 07:55 UTC, sunsidew commented on lib/Util/ProgressBar.php
> +        $this->proceed_php_cnt += 1;
위냐 아래냐에 따라 표시될 진행도가 ex) 0~99일지, 1~100일지의 차이라고 생각되는데요. 큰 차이는 없을거 같습니다.

2019-01-02 09:18 UTC, namenu commented on lib/Util/ProgressBar.php
> +        $this->proceed_php_cnt += 1;
@luaneyed 님께서 제안한 방향은 올바른 로직이고, 지금은 그렇지 않기 때문에 큰 차이입니다!
항상 모델이 먼저 수정되고 의존적인 뷰가 업데이트 되도록 해주세요 🙂

2019-01-03 02:47 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    private $total_php_cnt;
`ProgressBar`는 count의 대상이 `php file`인 것을 몰라도 됩니다.
변수명을 `$total_cnt`, `$proceed_cnt`로 하면 좋지 않을까요?

2019-01-03 02:58 UTC, luaneyed commented on lib/Converter.php
>              $this->getDirContents($this->source_dir_path, $this->last_src_name);
이번 작업 범위는 아니지만... ㅎㅎ `getDirContents` 함수의 정의가 지금 보니 어색해서 이번에 같이 수정되면 좋을 것 같습니다.

1. `get`보다는 `create`나 `make`같은 것이 어울릴 것 같습니다.
2. 함수 이름과 파라미터의 `dir`이 source인지  destination인지가 헷갈립니다.

2019-01-03 05:23 UTC, sunsidew commented on lib/Util/ProgressBar.php
> +        $this->proceed_php_cnt += 1;
@namenu 감사합니다 :)

2019-01-03 09:36 UTC, luaneyed commented on lib/Util/ProgressBar.php
> +    private $current_percent = 0;
이름과 의미가 틀린 것 같습니다.
뭐가 좋을지는 모르겠는데, (뭔가 이게 베스트는 아닌 것 같아요) `$next_updated_percent` 같은 의미가 맞지 않을까요?

2019-01-03 23:49 UTC, luaneyed approved these changes
👍

2019-01-04 08:02 UTC, merged